version: "3"
services:
  app:
      image: node:alpine
      volumes:
        - ./:/app
      working_dir: /app
      depends_on:
        - db
      environment:
        NODE_ENV: development
      ports:
        - 3000:3000
      command: npm run backend-dev
  frontend:
      image: node:alpine
      volumes:
        - ./:/app
      working_dir: /app/frontend
      environment:
        NODE_ENV: development
      ports:
        - 8080:8080
      command: npm run serve
  db:
    env_file:
      - .env
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
        - 3306:3306
    volumes:
      - trouble-ticket-db-volume:/var/lib/mysql
volumes:
  trouble-ticket-db-volume:
